Algoritmo "Escolha-caso - Mes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Escolher mês
// Autor(a)    : Bruss Loza
// Data atual  : 28/07/2026
Var
// Seção de Declarações das variáveis 
mes: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número entre 1 a 12 para saber o mês")
leia(mes)
escolha mes

caso 1
escreval("Janeiro")

caso 2
escreval("Fevereiro")

caso 3
escreval("Março")

caso 4
escreval("Abril")

caso 5
escreval("Maio")

caso 6
escreval("Junho")

caso 7
escreval("Julho")

caso 8
escreval("Agosto")

caso 9
escreval("Setembro")

caso 10
escreval("Outubro")

caso 11
escreval("Novembro")

caso 12
escreval("Dezembro")

outrocaso
escreval ("Você digitou um valor inválido")

fimescolha

Fimalgoritmo