Algoritmo "Escolha-caso"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Escolher o dia da semana
// Autor(a)    : Bruss Loza
// Data atual  : 28/07/2026
Var
// Seção de Declarações das variáveis 
diadasemana: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número entre 1 a 7 para saber o dia da semana")
leia(diadasemana)
escolha diadasemana

caso 1
escreval("domingo")

caso 2
escreval("Segunda-feira")

caso 3
escreval("Terça-feira")

caso 4
escreval("Quarta-feira")

caso 5
escreval("Quinta-feira")

caso 6
escreval("Sexta-feira")

caso 7
escreval("Sábado")

outrocaso
escreval ("Você digitou um valor inválido")

fimescolha

Fimalgoritmo