Algoritmo "Cálculo de combustível"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinícius
// Descrição   : Calcular o quanto se pagará para abastecer um automóvel
// Autor(a)    : Bruss
// Data atual  : 23/06/2026
Var
// Seção de Declarações das variáveis 
valorCombustivel, litrosCombustivel, resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor do combustível: ")
leia(valorCombustivel)
escreval("Digite a quantidade de litros abastecida: ")
leia(litrosCombustivel)
escreval("")

resultado <- valorCombustivel * litroscombustivel
escreval("O valor a ser pago será de R$ ",resultado)

Fimalgoritmo