Algoritmo "Custos de coelhos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
nr_coelhos,custo:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o número de coelhos.")
leia(nr_coelhos)

custo <- (nr_coelhos * 0.70) / 18 + 10

escreval("Os custos para a criação dos coelhos é de R$",custo)

Fimalgoritmo