Algoritmo "Escolha de curso"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
nome:caractere
curso:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o seu nome.")
leia(nome)
escreval("Escolha o curso que deseja comprar (entre 1 a 5)")
escreval("1 - Informática básica")
escreval("2 - Digitação")
escreval("3 - Lógica de programação")
escreval("4 - Linguagem de programação")
escreval("5 - Inteligência Artificial")

leia (curso)
escolha curso

caso 1
escreval("Aluno:",nome)
escreval("Curso escolhido: Informática básica")

caso 2
escreval("Aluno:",nome)
escreval("Curso escolhido: Digitação")

caso 3
escreval("Aluno:",nome)
escreval("Curso escolhido: Lógica de programação")

caso 4
escreval("Aluno:",nome)
escreval("Curso escolhido: Linguagem de programação")

caso 5
escreval("Aluno:",nome)
escreval("Curso escolhido: Inteligência Artificial")

outrocaso
escreval ("Você digitou um valor inválido")

fimescolha

Fimalgoritmo