Algoritmo "Número inteiro - Resultado do quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
numero,resultado1,resultado2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número.")
leia(numero)

resultado1 <- numero * numero
resultado2 <- numero * numero * numero

escreval("O quadrado desse número é",resultado1)
escreval("O cubo desse número é",resultado2)

Fimalgoritmo