Algoritmo "Valor entre 20 e 90"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   :
// Autor(a)    : Bruss Loza
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
valor:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um valor para verificar se ele esta entre 20 e 90")
leia(valor)

se(valor < 90) e (valor > 20) entao
escreval("O seu valor esta SIM entre 20 e 90")
senao
escreval("O seu valor NÃO esta entre 20 e 90")
fimse
Fimalgoritmo