Algoritmo "media da media"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   :
// Autor(a)    : Bruss Loza
// Data atual  : 05/08/2026
Var
// Seção de Declarações das variáveis 
media1, media2, media3, media4, media5, media6, media7, media8, mediaFinal:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a média do primeiro aluno:")
leia(media1)
escreval("Digite a média do segundo aluno:")
leia(media2)
escreval("Digite a média do terceiro aluno:")
leia(media3)
escreval("Digite a média do quarto aluno:")
leia(media4)
escreval("Digite a média do quinto aluno:")
leia(media5)
escreval("Digite a média do sexto aluno:")
leia(media6)
escreval("Digite a média do sétimo aluno:")
leia(media7)
escreval("Digite a média do oitavo aluno:")
leia(media8)

mediaFinal <-(media1 + media2 + media3 + media4 + media5 + media6 + media7 + media8) / 8

escreval("A média desses alunos é:",mediaFinal)
Fimalgoritmo