Algoritmo "vetornomePARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   :
// Autor(a)    : Bruss Loza
// Data atual  : 05/08/2026
Var
// Seção de Declarações das variáveis 
nome:vetor[0..4] de caractere
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 0 ate 4 faca
escreva("Digite o nome do colaborador:")
leia(nome[i])
fimpara
escreval("")
para i de 0 ate 4 faca
escreval("O nome dos nossos novos colaboradores são:",nome[i])
fimpara

Fimalgoritmo