Algoritmo "vetorsimples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   :
// Autor(a)    : Bruss Loza
// Data atual  : 05/08/2026
Var
// Seção de Declarações das variáveis 
vet:vetor[0..2] de real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número:")
leia(vet[0])
escreva("Digite um número:")
leia(vet[1])
escreva("Digite um número:")
leia(vet[2])
escreval("")
escreval("Os números digitados foram:",vet[0],vet[1],vet[2])

Fimalgoritmo