Algoritmo "Leitor de nome e idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinícius
// Descrição   : Vai receber o nome e a idade de uma pessoa e exibir na tela
// Autor(a)    : Bruss Loza
// Data atual  : 18/06/2026
Var
// Seção de Declarações das variáveis 
nome:caractere
idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o seu nome: ")
 leia (nome)
 escreval ("Digite a sua idade: ")
 leia (idade)
 escreval("O nome digitado é, ",nome," e a sua idade é ",idade)

Fimalgoritmo