Algoritmo "Média de 4 valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinícius
// Descrição   : Algoritmo para média de 4 valores
// Autor(a)    : Bruss Loza
// Data atual  : 18/06/2026
Var
// Seção de Declarações das variáveis
 media, valor1, valor2, valor3, valor4:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 escreval("Digite o primeiro valor")
 leia(valor1)
 escreval("Digite o segundo valor")
 leia(valor2)
 escreval("Digite o terceiro valor")
 leia(valor3)
 escreval("Digite o quarto valor")
 leia(valor4)

 media <- (valor1 + valor2 + valor3 + valor4) / 4

 escreval("O resultado da média dos valores é ",media)

Fimalgoritmo