Algoritmo "ValordaCompra5vezes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Autor(a)    : Bruss Loza
// Data atual  : 07/08/2026

Var
// Seção de Declarações das variáveis
valorCompra, parcela:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o valor de uma compra:")
leia(valorCompra)

parcela <- valorCompra / 5

escreval("O valor da sua compra é:",valorCompra)
escreval("Você pagará em 5 parcelas de:",parcela)


Fimalgoritmo