Algoritmo "Cálculo da Área do Triâgulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 19/06/2026
Var
// Seção de Declarações das variáveis
result, base, altura:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Cálculo da Área do Triâgulo")
escreval("Escreva a medida da base do triângulo")
leia(base)
escreval("Escreva a altura do Trângulo")
leia(altura)
result <- (base * altura) / 2
escreval("A área do triângulo é: ",result)

Fimalgoritmo