Algoritmo "Expressão Numérica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinícius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 19/06/2026
Var
// Seção de Declarações das variáveis 
 num1, num2, result:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 //Entrada de Dados
 num1 <- 2
 num2 <- 3
 
 //Processamento dos Dados
 result <- ((num1 + num2) * (num1 - num2)) / 4
 
 //Saída de Dados
 escreval("Cálculo da expressão ((a+b)*(a-b)) / 4")
 escreval("O resultado da expressão numérica é: ",result)

Fimalgoritmo