Algoritmo "Área do Retângulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Bruss Loza
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 19/06/2026
Var
// Seção de Declarações das variáveis 
result, ladoMenor, ladoMaior: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Cálculo da áre do Quadrado")
escreval("Digite o lado maior do retângulo")
leia(ladoMaior)
escreval("Digite o lado menor do retângulo")
leia(ladoMenor)
result <- ladoMaior * ladoMenor
escreval("A área do quadrado é: ",result,"m²")

Fimalgoritmo