Algoritmo "Área do Quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruss Loza
// Data atual  : 19/06/2026
Var
// Seção de Declarações das variáveis 
result, lado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Cálculo da áre do Quadrado")
escreval("Digite a medida de um dos lados do quadrado")
leia(lado)
result <- lado * lado
escreval("A área do quadrado é: ",result,"m²")

Fimalgoritmo